import { z } from "zod";

import {
  CredentialIdSchema,
  GrantIdSchema,
  PrincipalIdSchema,
  SpaceIdSchema,
  WorkspaceIdSchema,
  AgentRunIdSchema,
} from "./ids.js";

export const PrincipalKindSchema = z.enum([
  "human",
  "integration",
  "system",
  "agent",
]);
export type PrincipalKind = z.infer<typeof PrincipalKindSchema>;

export const RequestOriginSchema = z.enum([
  "desktop",
  "mobile",
  "import",
  "rule",
  "mcp",
  "maintenance",
]);
export type RequestOrigin = z.infer<typeof RequestOriginSchema>;

export const CapabilitySchema = z.enum([
  "workspace.createLocal",
  "workspace.rename",
  "workspace.bootstrapContext",
  "workspace.manageAccess",
  "workspace.access",
  "workspace.exportScoped",
  "capture.submit",
  "capture.process",
  "capture.audioRead",
  "capture.transcriptWrite",
  "capture.audioDeleteConfirm",
  "capture.submitText",
  "capture.routeAsTask",
  "capture.history",
  "project.create",
  "project.updateOutcome",
  "project.list",
  "project.operationalOverview",
  "document.create",
  "document.list",
  "knowledge.sourceCreate",
  "knowledge.sourceUpdate",
  "knowledge.documentSetEvidence",
  "knowledge.namedVersionCreate",
  "knowledge.namedVersionVoid",
  "knowledge.list",
  "knowledge.documentContext",
  "relationship.organizationCreate",
  "relationship.personCreate",
  "opportunity.create",
  "opportunity.offerCreate",
  "opportunity.linkOutcomes",
  "relationship.workspace",
  "relationship.renewalCreate",
  "relationship.renewalResolve",
  "relationship.factCreate",
  "decision.create",
  "decision.supersede",
  "decision.resolveImpact",
  "area.create",
  "initiative.create",
  "work.linkCreate",
  "work.linkRemove",
  "savedView.create",
  "task.setOperationalState",
  "work.overview",
  "recurrence.create",
  "recurrence.generateOccurrence",
  "project.close",
  "project.reopen",
  "radar.candidateUpsert",
  "radar.resolve",
  "radar.review",
  "meeting.upsertImported",
  "task.create",
  "task.updateDetails",
  "task.setParent",
  "template.create",
  "template.rename",
  "template.updateContents",
  "template.archive",
  "template.restore",
  "project.applyTemplate",
  "fieldDef.create",
  "fieldDef.rename",
  "fieldDef.archive",
  "fieldDef.restore",
  "record.setFieldValue",
  "taskStatus.create",
  "taskStatus.rename",
  "taskStatus.setSemantics",
  "taskStatus.reorder",
  "taskStatus.archive",
  "taskStatus.restore",
  "workspace.setDefaultTaskStatus",
  "task.setStatus",
  "task.complete",
  "task.reopen",
  "task.assign",
  "task.unassign",
  "record.relate",
  "record.unrelate",
  "search.global",
  "cockpit.week",
  "activity.meaningful",
  "command.previewUndo",
  "command.undo",
  "recovery.preview",
  "task.list",
  "task.assignmentCandidates",
  "comment.add",
  "comment.edit",
  "comment.resolve",
  "comment.reopen",
  "comment.list",
  "comment.mentionCandidates",
  "attention.inbox",
  "attention.markRead",
  "attention.dismiss",
  "audit.receipt",
  "agent.manageAccess",
  "agent.access",
  "agent.checkpoint.create",
  "agent.checkpoint.previewRevert",
  "agent.checkpoint.revert",
  "agent.handoff.submit",
]);
export type Capability = z.infer<typeof CapabilitySchema>;

export const ExecutionContextSchema = z
  .object({
    principalId: PrincipalIdSchema,
    principalKind: PrincipalKindSchema,
    delegatingUserId: PrincipalIdSchema.optional(),
    credentialId: CredentialIdSchema,
    grantId: GrantIdSchema,
    policyVersion: z.int().positive(),
    workspaceId: WorkspaceIdSchema,
    spaceScope: z.array(SpaceIdSchema).min(1),
    capabilityScope: z.array(CapabilitySchema).min(1),
    origin: RequestOriginSchema,
    hostRun: z
      .object({
        runId: z.string().trim().min(1).max(200),
        parentRunId: z.string().trim().min(1).max(200).optional(),
        intent: z.string().trim().min(1).max(500).optional(),
        agentRunId: AgentRunIdSchema.optional(),
        hostName: z.string().trim().min(1).max(120).optional(),
        hostVersion: z.string().trim().min(1).max(120).optional(),
        modelProvider: z.string().trim().min(1).max(120).optional(),
        modelName: z.string().trim().min(1).max(200).optional(),
      })
      .strict()
      .optional(),
  })
  .strict();

export type ExecutionContext = z.infer<typeof ExecutionContextSchema>;
