import assert from "node:assert/strict";
import { describe, it } from "node:test";

import * as Y from "yjs";

import {
  DOCUMENT_FORMAT_METADATA_ROOT,
  READABLE_STRUCTURED_DOCUMENT_SCHEMA_VERSIONS,
  STRUCTURED_DOCUMENT_SCHEMA_VERSION,
  YjsRealtimeDocumentAdapter,
  parseStructuredDocument,
} from "../src/index.js";
import {
  V1_RICH_DOCUMENT_CONTENT,
  V1_RICH_DOCUMENT_STATE_BASE64,
  V1_RICH_DOCUMENT_TEXT,
} from "./v1-rich-document-fixture.js";

/**
 * The version was enforced by a hard `!==` against the writing constant, in
 * `parseStructuredDocument` — which every agent read, every idempotency digest
 * and every restore comparison passes through. So moving the constant to 2 on
 * its own would have made every note that exists today unreadable and
 * unwritable to every agent, at once. That is the same defect as the h4 note
 * S1 closed, except that this one is total.
 *
 * Nothing here is pinned to a literal 2. A wave that moves the version to 3
 * must not be able to make these pass by regenerating the fixture.
 */

const v1State = (): Uint8Array =>
  Uint8Array.from(Buffer.from(V1_RICH_DOCUMENT_STATE_BASE64, "base64"));

const uuid = "c0000000-0000-4000-8000-000000000002";

// ProseMirror hands attributes back on null-prototype objects, which strict
// deep equality distinguishes from the committed literal. The property being
// asserted is the CONTENT, and JSON is the shape every consumer of it — the
// idempotency digest, the restore comparison, the MCP response — actually
// sees.
const plain = (value: unknown): unknown =>
  JSON.parse(JSON.stringify(value)) as unknown;

const documentAt = (schemaVersion: number, node: unknown) => ({
  schemaVersion,
  type: "doc",
  content: [node],
});

const image = {
  type: "image",
  attrs: { sourceId: uuid, alt: "A whiteboard" },
};

const table = {
  type: "table",
  content: [
    {
      type: "tableRow",
      content: [
        {
          type: "tableHeader",
          content: [
            { type: "paragraph", content: [{ type: "text", text: "Budget" }] },
          ],
        },
      ],
    },
  ],
};

describe("the content schema version", () => {
  it("declares itself readable, and keeps the first version readable", () => {
    // Derived on both sides. `deepEqual([1, 2])` would turn red the day a
    // version 3 arrives and would tempt whoever met it to edit the assertion
    // rather than think about what stopped being readable.
    assert.ok(
      READABLE_STRUCTURED_DOCUMENT_SCHEMA_VERSIONS.includes(
        STRUCTURED_DOCUMENT_SCHEMA_VERSION,
      ),
      "The build cannot read what it writes.",
    );
    assert.ok(
      (
        READABLE_STRUCTURED_DOCUMENT_SCHEMA_VERSIONS as readonly number[]
      ).includes(1),
      "Version 1 stopped being readable, and every note in the vault is one.",
    );
  });

  it("still reads a document the shipped v1 build wrote", () => {
    const document = new Y.Doc({ gc: true });
    try {
      Y.applyUpdate(document, v1State(), { kind: "remote" });
      // Instrument check first: if this fixture were ever regenerated by the
      // current build it would carry the CURRENT version, and every assertion
      // below would go on passing while proving nothing about the old one.
      assert.equal(
        document
          .getMap<unknown>(DOCUMENT_FORMAT_METADATA_ROOT)
          .get("schemaVersion"),
        1,
        "The committed fixture is no longer the v1 artefact — it was regenerated, and it is the only evidence there is.",
      );
    } finally {
      document.destroy();
    }

    const adapter = new YjsRealtimeDocumentAdapter(v1State());
    try {
      const read = adapter.getStructuredContent();
      assert.equal(read.schemaVersion, STRUCTURED_DOCUMENT_SCHEMA_VERSION);
      // The property that matters is not the number, it is that nothing of the
      // old content was lost or changed on the way through.
      assert.deepEqual(plain(read.content), V1_RICH_DOCUMENT_CONTENT);
      assert.equal(adapter.getText(), V1_RICH_DOCUMENT_TEXT);
    } finally {
      adapter.destroy();
    }
  });

  it("accepts a v1 document handed straight to the validator", () => {
    const parsed = parseStructuredDocument({
      schemaVersion: 1,
      type: "doc",
      content: V1_RICH_DOCUMENT_CONTENT,
    });
    assert.equal(parsed.schemaVersion, STRUCTURED_DOCUMENT_SCHEMA_VERSION);
    assert.deepEqual(plain(parsed.content), V1_RICH_DOCUMENT_CONTENT);
  });

  it("refuses a version it does not read at all", () => {
    for (const version of [
      0,
      "1",
      null,
      STRUCTURED_DOCUMENT_SCHEMA_VERSION + 1,
    ]) {
      assert.throws(
        () =>
          parseStructuredDocument(
            documentAt(version as number, {
              type: "paragraph",
              content: [{ type: "text", text: "x" }],
            }),
          ),
        /DOCUMENT_STRUCTURED_SCHEMA_INVALID/u,
        `Version ${String(version)} is not readable and must be refused.`,
      );
    }
  });

  it("refuses content carrying a node the declared version did not have", () => {
    // This is what makes the number mean something rather than decorate the
    // request: a caller that says 1 gets version 1's vocabulary, so it cannot
    // put a node into a document that a reader pinned to 1 would have to
    // invent a rendering for.
    for (const node of [image, table]) {
      assert.throws(
        () => parseStructuredDocument(documentAt(1, node)),
        /DOCUMENT_STRUCTURED_SCHEMA_VERSION_TOO_OLD/u,
        `A ${node.type} is not part of version 1 and must be refused there.`,
      );
      assert.doesNotThrow(() =>
        parseStructuredDocument(
          documentAt(STRUCTURED_DOCUMENT_SCHEMA_VERSION, node),
        ),
      );
    }
  });

  it("stamps the current version into the metadata a document carries", () => {
    // OPEN-3: these two writes were the literal `1`, tied to nothing, read by
    // nobody. Nothing observes the value even now — which is exactly why it
    // could sit at 1 while the schema it names moved.
    const adapter = new YjsRealtimeDocumentAdapter();
    const origin = { kind: "human", principalId: "kacper" } as const;
    try {
      adapter.migrateToRich("a".repeat(64), origin);
      const checkpoint = adapter.checkpoint();
      const document = new Y.Doc({ gc: true });
      try {
        Y.applyUpdate(document, checkpoint.state, { kind: "remote" });
        assert.equal(
          document
            .getMap<unknown>(DOCUMENT_FORMAT_METADATA_ROOT)
            .get("schemaVersion"),
          STRUCTURED_DOCUMENT_SCHEMA_VERSION,
        );
      } finally {
        document.destroy();
      }
    } finally {
      adapter.destroy();
    }
  });
});
