/**
 * A rich document produced by the SHIPPED v1 build — `main` @1edcf40, before
 * `STRUCTURED_DOCUMENT_SCHEMA_VERSION` moved to 2 — carrying every node kind
 * and every mark that version 1 had.
 *
 * It is committed BYTES, not a document the test builds at run time, and that
 * is the whole value of it: a fixture regenerated by the current build proves
 * only that the current build agrees with itself. These bytes were written by
 * the code that wrote every note in the vault today.
 *
 * What it guards: `parseStructuredDocument` enforced the version with a hard
 * `!==` against the constant, so bumping the constant alone would have made
 * every existing note unreadable AND unwritable to every agent at once — the
 * same shape as the h4 defect, except total. Regenerating this file to make a
 * test pass would delete the only evidence that did not happen.
 */
export const V1_RICH_DOCUMENT_STATE_BASE64 =
  "AUe45NXJCgAEAQdjb250ZW50BHNlZWQHAQxyaWNoLWNvbnRlbnQDCXBhcmFncmFwaAcA" +
  "uOTVyQoEBgEAuOTVyQoFBCgBFmNvbnN0ZWxsYXRpb24tZG9jdW1lbnQGZm9ybWF0AXcH" +
  "cmljaC12MSgBFmNvbnN0ZWxsYXRpb24tZG9jdW1lbnQNc2NoZW1hVmVyc2lvbgF9ASgB" +
  "FmNvbnN0ZWxsYXRpb24tZG9jdW1lbnQMbGVnYWN5RGlnZXN0AXdAYWFhYWFhYWFhYWFh" +
  "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh" +
  "YUe45NXJCgQDB2hlYWRpbmcHALjk1ckKDQYEALjk1ckKDg5XYXZlIEQgZml4dHVyZSgA" +
  "uOTVyQoNBWxldmVsAX0Bx7jk1ckKDbjk1ckKBAMHaGVhZGluZwcAuOTVyQoeBgQAuOTV" +
  "yQofGGg0LCB0aGUgbGV2ZWwgUzEgd2lkZW5lZCgAuOTVyQoeBWxldmVsAX0Ex7jk1ckK" +
  "Hrjk1ckKBAMJcGFyYWdyYXBoBwC45NXJCjkGBAC45NXJCjoHcGxhaW4sIIa45NXJCkEE" +
  "Ym9sZAJ7fYS45NXJCkIEYm9sZIa45NXJCkYEYm9sZARudWxshLjk1ckKRwIsIIa45NXJ" +
  "CkkGaXRhbGljAnt9hLjk1ckKSgZpdGFsaWOGuOTVyQpQBml0YWxpYwRudWxshLjk1ckK" +
  "UQIsIIa45NXJClMGc3RyaWtlAnt9hLjk1ckKVAZzdHJpa2WGuOTVyQpaBnN0cmlrZQRu" +
  "dWxshLjk1ckKWwIsIIa45NXJCl0JdW5kZXJsaW5lAnt9hLjk1ckKXgl1bmRlcmxpbmWG" +
  "uOTVyQpnCXVuZGVybGluZQRudWxshLjk1ckKaAIsIIa45NXJCmoEY29kZQJ7fYS45NXJ" +
  "CmsEY29kZYa45NXJCm8EY29kZQRudWxshLjk1ckKcAIsIIa45NXJCnIEbGlua3F7Imhy" +
  "ZWYiOiJodHRwczovL2V4YW1wbGUub3JnL2EiLCJ0YXJnZXQiOiJfYmxhbmsiLCJyZWwi" +
  "OiJub29wZW5lciBub3JlZmVycmVyIG5vZm9sbG93IiwiY2xhc3MiOm51bGwsInRpdGxl" +
  "IjpudWxsfYS45NXJCnMEbGlua4a45NXJCncEbGluawRudWxsh7jk1ckKOgMJaGFyZEJy" +
  "ZWFrh7jk1ckKeQYEALjk1ckKeiVhZnRlciBhIGhhcmQgYnJlYWssIGFuZCBhIHJlZmVy" +
  "ZW5jZTogh7jk1ckKegMPZW50aXR5UmVmZXJlbmNlKAC45NXJCqABCnRhcmdldEtpbmQB" +
  "dwR0YXNrKAC45NXJCqABCHRhcmdldElkAXckYzAwMDAwMDAtMDAwMC00MDAwLTgwMDAt" +
  "MDAwMDAwMDAwMDAxx7jk1ckKObjk1ckKBAMKYmxvY2txdW90ZQcAuOTVyQqjAQMJcGFy" +
  "YWdyYXBoBwC45NXJCqQBBgQAuOTVyQqlAQZxdW90ZWTHuOTVyQqjAbjk1ckKBAMKYnVs" +
  "bGV0TGlzdAcAuOTVyQqsAQMIbGlzdEl0ZW0HALjk1ckKrQEDCXBhcmFncmFwaAcAuOTV" +
  "yQquAQYEALjk1ckKrwEFZmlyc3SHuOTVyQqtAQMIbGlzdEl0ZW0HALjk1ckKtQEDCXBh" +
  "cmFncmFwaAcAuOTVyQq2AQYEALjk1ckKtwEGc2Vjb25kx7jk1ckKrAG45NXJCgQDC29y" +
  "ZGVyZWRMaXN0BwC45NXJCr4BAwhsaXN0SXRlbQcAuOTVyQq/AQMJcGFyYWdyYXBoBwC4" +
  "5NXJCsABBgQAuOTVyQrBAQV0aGlyZCgAuOTVyQq+AQVzdGFydAF9A8e45NXJCr4BuOTV" +
  "yQoEAwljb2RlQmxvY2sHALjk1ckKyAEGBAC45NXJCskBDGNvbnN0IHggPSAxOygAuOTV" +
  "yQrIAQhsYW5ndWFnZQF3CnR5cGVzY3JpcHTHuOTVyQrIAbjk1ckKBAMOaG9yaXpvbnRh" +
  "bFJ1bGUBuOTVyQoBBgQ=";

/** The content the v1 build round-tripped these bytes to, verbatim. */
export const V1_RICH_DOCUMENT_CONTENT = [
  {
    type: "heading",
    attrs: {
      level: 1,
    },
    content: [
      {
        type: "text",
        text: "Wave D fixture",
      },
    ],
  },
  {
    type: "heading",
    attrs: {
      level: 4,
    },
    content: [
      {
        type: "text",
        text: "h4, the level S1 widened",
      },
    ],
  },
  {
    type: "paragraph",
    content: [
      {
        type: "text",
        text: "plain, ",
      },
      {
        type: "text",
        marks: [
          {
            type: "bold",
          },
        ],
        text: "bold",
      },
      {
        type: "text",
        text: ", ",
      },
      {
        type: "text",
        marks: [
          {
            type: "italic",
          },
        ],
        text: "italic",
      },
      {
        type: "text",
        text: ", ",
      },
      {
        type: "text",
        marks: [
          {
            type: "strike",
          },
        ],
        text: "strike",
      },
      {
        type: "text",
        text: ", ",
      },
      {
        type: "text",
        marks: [
          {
            type: "underline",
          },
        ],
        text: "underline",
      },
      {
        type: "text",
        text: ", ",
      },
      {
        type: "text",
        marks: [
          {
            type: "code",
          },
        ],
        text: "code",
      },
      {
        type: "text",
        text: ", ",
      },
      {
        type: "text",
        marks: [
          {
            type: "link",
            attrs: {
              href: "https://example.org/a",
              target: "_blank",
              rel: "noopener noreferrer nofollow",
              class: null,
              title: null,
            },
          },
        ],
        text: "link",
      },
      {
        type: "hardBreak",
      },
      {
        type: "text",
        text: "after a hard break, and a reference: ",
      },
      {
        type: "entityReference",
        attrs: {
          targetKind: "task",
          targetId: "c0000000-0000-4000-8000-000000000001",
        },
      },
    ],
  },
  {
    type: "blockquote",
    content: [
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: "quoted",
          },
        ],
      },
    ],
  },
  {
    type: "bulletList",
    content: [
      {
        type: "listItem",
        content: [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: "first",
              },
            ],
          },
        ],
      },
      {
        type: "listItem",
        content: [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: "second",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "orderedList",
    attrs: {
      start: 3,
      type: null,
    },
    content: [
      {
        type: "listItem",
        content: [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: "third",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "codeBlock",
    attrs: {
      language: "typescript",
    },
    content: [
      {
        type: "text",
        text: "const x = 1;",
      },
    ],
  },
  {
    type: "horizontalRule",
  },
  {
    type: "paragraph",
  },
] as const;

/** The plain text the v1 build extracted from these bytes, verbatim. */
export const V1_RICH_DOCUMENT_TEXT =
  "Wave D fixture\nh4, the level S1 widened\nplain, bold, italic, strike, underline, code, link\nafter a hard break, and a reference: \nquoted\nfirst\nsecond\nthird\nconst x = 1;\n\n";
